# declare language
language: python
# declare versions to test
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
# dependencies installation
install: "pip install psutil"
install: "pip install cython"
install: "pip install vedis"
install: "pip install flask"
# command to run tests
script: nosetests