env:
  global:
     secure: "M6l2LSV2tU76FDKYO3Bd9j+i9jj8S8Ehzfl3lHoWhAVeDh7uBPcYrqAvbmmPDYXFl1n3wzNNufqf3FKPh5rpF6+TCfDiiUqQ2nq5em98V6OJrbhqwJCkRehfaPPkWdfLN5nLr7w1kZ7B+JoY2Kx2dwzc0rg90VD4eCnrwKlpfTueKriHSb6m+COMDDntQtUqieTx4WXN1dz4F20bTu3F0QOVlLDS9cW6hwhYIvoCWK1JIpiXT2C6yXXK+CQeumrF+M3KSBfcULDX7qr0+buRzhDldixvD7tfzdeAgY/UVDn6hGS5jy0wSKRL1q2lLCZ0+w9eMsMh0lCG/xprvwIcEFMwgFepUZfYymEzKQz/FqK8pyOeXFoYxmEHz+vSF6dQKFWfpDhYbtgZZRvhkRFSBjEnc0Lau7AUfgFZsbTzfoY8bsPKhXvJ1vvDJTvTP7YksVPrkGC5pXflDftY6x0MzqCA7y8nHK65oDDDXuBL7aIEZArGaxusFGRw8qCjMZn5dp7PR8HOv8scqOmJENciTKQCAEI45dUslFqzzWAeM6lpymo2XsW9o9p1wCq6clnfD+nQtoX2m8Cj9WxflYqOZ7vAM+kjGi55WllShifXWENx1F93fXUwFzIAX/qRr7yq0csqyin7pLTpIB/0yvUXLzFLQX721wfPE+1hPcy93Jg="

install:
- npm install -g bower

script:
# Save the latest SHa of the frontend
- SHA=`git rev-parse --verify --short HEAD`

# Clone the gh-pages branch of the backend to the local env
- cd ..
- git clone "https://github.com/OpServ-Monitoring/opserv-backend.git" --branch gh-pages --single-branch website

# Exchange the current demo with the latest commit
- cd website/docs/guide/
- rm -rf demo
- cp -r /home/travis/build/OpServ-Monitoring/opserv-frontend demo

# Install the needed dependencies for the web-interface
- cd demo
- bower install

# Remove unwanted files
- rm .gitignore # bower components are gitignored in the frontend-repo
- rm -rf .git

- cd /home/travis/build/OpServ-Monitoring/website

# Config git
- git config --global user.email "admin@opserv.org"
- git config --global user.name "OpServ-Admin"
- git remote set-url origin "https://OpServ-Admin:${GITHUB_AUTH_KEY}@github.com/OpServ-Monitoring/opserv-backend.git"

# Commit the changes
- git add .
- git commit -m"Automated push - Update web-interface demo. Triggering opserv-frontend commit -> ${SHA}"

# Push the changes
- ls -laR
- pwd
- git push origin gh-pages # TODO Throw push error away

